[package]
name = "bazalbuilder/lunit"
description = "Luau testing made easy."
version = "0.1.2-alpha"
license = "MIT"
authors = ["Bazalbuilder"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/Bazalbuilder/Lunit"

[dependencies]
